#!/usr/bin/env python3
"""Turn resources/wdcs_legacy_baptisms.csv into SQL that loads the historical
baptism record into the friend table.

    python scripts/load_backfill.py --csv resources/wdcs_legacy_baptisms.csv --sql out.sql
    npx wrangler d1 execute dcsm_ki --remote --file out.sql

Every row -> a confirmed baptism (baptized_confirmed = 1), source kept granular,
confidence = 'unverified' when the only source is the Zone Leader form else
'confirmed'. Re-runnable: it deletes prior backfill rows first.
"""

from __future__ import annotations

import argparse
import csv
import re
import unicodedata
import uuid

NOW = "2026-09-01T00:00:00Z"


def fold(s: str) -> str:
    s = unicodedata.normalize("NFKD", s or "").encode("ascii", "ignore").decode()
    return re.sub(r"\s+", " ", s).strip().lower()


def q(v) -> str:
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default="resources/wdcs_legacy_baptisms.csv")
    ap.add_argument("--sql", default="backfill.sql")
    args = ap.parse_args()

    with open(args.csv, encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))

    lines = [
        "-- generated by scripts/load_backfill.py",
        "DELETE FROM friend_week WHERE friend_id IN (SELECT id FROM friend WHERE source NOT IN ('sheet','portal'));",
        "DELETE FROM friend WHERE source NOT IN ('sheet','portal');",
    ]
    used_keys: set[str] = set()
    n_conf = n_unv = n_nokey = 0

    for r in rows:
        name = (r.get("name") or "").strip()
        if not name:
            continue
        ward = (r.get("ward") or "").strip()
        stake = (r.get("stake") or "").strip()
        zone = (r.get("zone") or "").strip()
        miss = (r.get("missionaries") or "").strip()
        bd = (r.get("baptism_date") or "").strip()
        src = (r.get("source") or "legacy").strip()
        notes = (r.get("notes") or "").strip()
        conf = "unverified" if src == "zl_form_response" else "confirmed"
        if conf == "unverified":
            n_unv += 1
        else:
            n_conf += 1

        # No sync_key for backfill rows: they're historical, never re-entered in
        # the working sheet, and a NULL avoids any collision with a live record.
        key = ""
        n_nokey += 1

        confirmed_at = f"{bd}T00:00:00Z" if bd else NOW
        lines.append(
            "INSERT INTO friend (id,name,zone,ward,stake,missionaries,baptism_date,"
            "baptized_confirmed,confirmed_at,dropped,active,source,confidence,notes,sync_key,"
            "created_at,created_by,updated_at,updated_by) VALUES ("
            f"{q(str(uuid.uuid4()))},{q(name)},{q(zone)},{q(ward)},{q(stake)},{q(miss)},{q(bd)},"
            f"1,{q(confirmed_at)},0,1,{q(src)},{q(conf)},{q(notes)},{q(key or None)},"
            f"{q(NOW)},'backfill',{q(NOW)},'backfill');"
        )

    with open(args.sql, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"{len(rows)} rows -> {args.sql}")
    print(f"  confirmed: {n_conf}   unverified (ZL form only): {n_unv}")
    print(f"  sync_key suppressed for {n_nokey} (blank ward or collision)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
